site_name: 'Aragon Wiki'
site_url: https://wiki.aragon.one
repo_name: 'aragon/aragon-wiki'
repo_url: 'https://github.com/aragon/aragon-wiki'
site_description: 'Wiki for the Aragon Project'
theme:     'material'
site_favicon: 'images/favicon.ico'
extra_css:
  - 'stylesheets/extra.css'
extra:
  palette:
    primary: 'blue grey'
    accent:  'cyan'
  logo:    'images/logo.svg'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/aragon'
    - type: 'medium'
      link: 'https://blog.aragon.one/'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/aragonproject/'
    - type: 'twitter'
      link: 'https://twitter.com/AragonProject'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/aragonproject/'
  feature:
    tabs: false
pages:
  - Home: 'index.md'
  - Documentation:
    - Whitepaper: 'documentation/whitepaper.md'
    - Governance:
      - AGP2 - Community Governance Model: 'documentation/Community_Governance_Model.md'
      - AGP5 - Migration to Open Source Messaging Platform: 'documentation/Migration_to_Open_Source_Messaging_Platform.md'
      - AGP7 - Merge Aragon HQ and Community meetings: 'documentation/Merge_Aragon_HQ_and_Community_meetings.md'
    - Multisigs:
      - Overview: 'documentation/multisigs/overview.md'
      - Foundation: 'documentation/multisigs/foundation.md'
      - Community: 'documentation/multisigs/community.md'
    - Development Plan: 'documentation/Development_Plan.md'
    - Aragon Code of Conduct: 'documentation/Code_of_Conduct.md'
    - Presentations: 'documentation/presentations.md'
    - Audit reports:
      - Audit 01 by Adam Dossa: 'documentation/audits/audit01_report_dossa.md'
  - Development:
    - Overview: 'dev/index.md'
    - AragonOS: 'dev/AragonOS.md'
    - aragon-core:
      - Overview: 'dev/aragon-core_home.md'
      - How to contribute: 'dev/aragon-core_how_to_contribute.md'
    - Aragon Apps:
      - Overview: 'dev/apps/index.md'
      - Voting: 'dev/apps/voting.md'
      - Token Manager: 'dev/apps/token-manager.md'
      - Group: 'dev/apps/group.md'
      - Fundraising: 'dev/apps/fundraising.md'
      - Vault: 'dev/apps/vault.md'
      - Finance: 'dev/apps/finance.md'
  - Design:
    - Overview: 'design/index.md'
    - Logo: 'design/logo/index.md'
    - Identity Guidelines: 'design/identity_guidelines.md'
    - Branding Proposal: 'design/branding_proposal.md'
    - Merchandise: 'design/merch/index.md'
  - Meetings:
    - Community:
      - Community 07:
        - Agenda: 'meetings/community/07.md'
        - Write-Up - Alexa: 'meetings/community/write-ups/cm07/alexa.md'
        - Write-Up - Brett: 'meetings/community/write-ups/cm07/brett.md'
        - Write-Up - John: 'meetings/community/write-ups/cm07/light-cm07.md'
        - Write-Up - Jorge: 'meetings/community/write-ups/cm07/jorge.md'
        - Write-Up - Luis: 'meetings/community/write-ups/cm07/luis.md'
        - Write-Up - Luke: 'meetings/community/write-ups/cm07/luke.md'
        - Write-Up - Maria: 'meetings/community/write-ups/cm07/maria.md'
        - Write-Up - Oliver: 'meetings/community/write-ups/cm07/oliver.md'
        - Write-Up - Pierre: 'meetings/community/write-ups/cm07/pierre.md'
        - Write-Up - Tatu: 'meetings/community/write-ups/cm07/tatu.md'
      - Community 06:
        - Agenda: 'meetings/community/06.md'
        - Write-Up - Brett: 'meetings/community/write-ups/cm06/brett.md'
        - Write-Up - John: 'meetings/community/write-ups/cm06/john.md'
        - Write-Up - Jorge: 'meetings/community/write-ups/cm06/jorge.md'
        - Write-Up - Luis: 'meetings/community/write-ups/cm06/luis.md'
        - Write-Up - Luke: 'meetings/community/write-ups/cm06/luke.md'
        - Write-Up - Maria: 'meetings/community/write-ups/cm06/maria.md'
        - Write-Up - Oliver: 'meetings/community/write-ups/cm06/oliver.md'
        - Write-Up - Pierre: 'meetings/community/write-ups/cm06/pierre.md'
        - Write-Up - Tatu: 'meetings/community/write-ups/cm06/tatu.md'
      - Community 05: 'meetings/community/05.md'
      - Community 04: 'meetings/community/04.md'
      - Community 03: 'meetings/community/03.md'
      - Community 02: 'meetings/community/02.md'
      - Community 01: 'meetings/community/01.md'
  - Jobs:
    - Overview: 'jobs/index.md'
    - Openings:
      - EVM/Solidity Engineer: 'jobs/openings/solidity.md'
      - Frontend and web3 Developer: 'jobs/openings/frontend.md'
      - Product Manager: 'jobs/openings/product_manager.md'
      - Developer Relations: 'jobs/openings/dev_rel.md'
      - Design Lead: 'jobs/openings/design.md'
  - Blog posts:
    - 2017: 'blog/2017.md'
  - Videos:
    - Tutorials: 'videos/tutorials.md'
    - Meetings:
      - Community: 'videos/community.md'
    - Interviews: 'videos/interviews.md'
    - Presentations: 'videos/presentations.md'
  - Press:
      - Press Kit: 'press/press-kit.md'
      - Media Mentions: 'press/media-mentions.md'
      - Contact: 'press/contact.md'
  - Archive:
    - Documentation:
      - AGP5 - Rocket Chat comparison: 'archive/documentation/agp5/RocketChat.md'
      - AGP5 - Riot comparison: 'archive/documentation/agp5/Riot.md'
    - Meetings:
      - Aragon HQ:
        - HQ 01: 'archive/meetings/hq/01.md'
        - HQ 02: 'archive/meetings/hq/02.md'
        - HQ 03: 'archive/meetings/hq/03.md'
      - Dev:
        - Dev 01: 'archive/meetings/dev/01.md'
        - Dev 02: 'archive/meetings/dev/02.md'
    - Videos:
      - Meetings:
        - Aragon HQ: 'archive/videos/hq.md'
        - Dev: 'archive/videos/dev.md'
  - Translations:
    - Spanish:
      - Hola: 'translations/spanish/index.md'
